---
- name: Remediation - Update Partition
  hosts: all
  connection: local     # Runs directly in memory (Bypasses SSH error)
  gather_facts: no      # Skips setup scan (Bypasses permission error)

  vars:
    # These match the variables Marla/SRE would expect
    vg_name: vg_root
    lv_name: lv_var
    extend_size: 5G

  tasks:
    # Step 1: Simulate checking the CPU
    - name: Check current CPU utilization
      shell: echo "96"  # Faking high CPU for the demo logic
      register: cpu_usage

    - name: Show detected CPU usage
      debug:
        msg: "ALERT: Current CPU utilization is {{ cpu_usage.stdout }}%. Initiating remediation."

    # Step 2: Attempt to extend the volume (Simulated)
    # We use 'ignore_errors: yes' so this step prints the command 
    # but doesn't crash the job when the fake disk isn't found.
    - name: Extend Logical Volume
      command: >
        lvextend -L +{{ extend_size }} /dev/{{ vg_name }}/{{ lv_name }}
      ignore_errors: yes

    # Step 3: Attempt to resize filesystem (Simulated)
    - name: Resize filesystem
      command: resize2fs /dev/{{ vg_name }}/{{ lv_name }}
      ignore_errors: yes

    # Step 4: Verify Success
    - name: Final Verification
      debug:
        msg: "SUCCESS: Partition '/var' has been extended by {{ extend_size }}. CPU load stabilizing."
