---
- name: Checking New Version   # <--- If you don't see this name in logs, Sync failed.
  hosts: all
  connection: local            # Fixes SSH error
  gather_facts: no             # Fixes 'Gathering Facts' error
  tasks:
    - name: Confirmation Message
      debug:
        msg: "SUCCESS! You are running the UPDATED script."
